name: test-env
channels:
  - conda-forge
  - defaults
dependencies:
  - pyldavis
  - rise
  - ipyparallel
  - nbformat=5.0.8
  - regex
  - sqlalchemy
  - jupyter_nbextensions_configurator
  - scikit-learn
  - pyodbc
  - pip
  - python=3.9
  - pandas
  - jupyterlab=3
  - beautifulsoup4
